### ISSUE TITLE
ERROR:asyncio:Unclosed client session

### ISSUE THREAD

**Issue by APTEMOH** [kesha1225/pykwork#2]
Hi!

`INFO:root:Bot is running!
INFO:kwork.kwork:Starting listen messages
Traceback (most recent call last):
  File "bot.py", line 46, in <module>
    loop.run_until_complete(run())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "bot.py", line 42, in run
    await bot.run_bot()
  File "/usr/local/lib/python3.7/site-packages/kwork/kwork.py", line 353, in run_bot
    async for message in self.listen_messages():
  File "/usr/local/lib/python3.7/site-packages/kwork/kwork.py", line 288, in listen_messages
    event.data["dialog_data"][0]["login"]
KeyError: 'dialog_data'
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f27b9d12c10>
INFO:root:Bot is running!
INFO:kwork.kwork:Starting listen messages`

**Comment by JustLike420** [comment]
bump

**Comment by kesha1225** [comment]
`await api.close()` https://github.com/kesha1225/pykwork/blob/5e67db728ddb52f3452436ce51a794350d1734ed/api_example.py#L73

**Comment by kesha1225** [comment]
у вас тут другая ошибка вообще, просто в конце сессия не закрыта, твоя ошибка это ` event.data["dialog_data"][0]["login"] KeyError: 'dialog_data'`
